apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: titikshaacr08.azurecr.io/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: ORDER_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-w08e1     # <-- use existing ConfigMap
                  key: ORDER_SERVICE_URL       # <-- map to existing key
            - name: PRODUCT_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-w08e1
                  key: PRODUCT_SERVICE_URL
      imagePullSecrets:
        - name: acr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w08e1
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80