apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w08e1
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
        - name: order-service-container
          image: titikshaacr08.azurecr.io/order_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # DB config
            - name: POSTGRES_HOST
              value: order-db-service-w08e1
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-w08e1
                  key: ORDERS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_PASSWORD
            # Internal URL to Product API (service-to-service)
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service-w08e1:8000"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w08e1
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8000
      protocol: TCP
