apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-w08e1
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: acr-creds
      containers:
        - name: product-service-container
          image: titikshaacr08.azurecr.io/product_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # DB config
            - name: POSTGRES_HOST
              value: product-db-service-w08e1
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-w08e1
                  key: PRODUCTS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: POSTGRES_PASSWORD
            # Azure Storage for uploads
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-w08e1
                  key: AZURE_STORAGE_ACCOUNT_KEY
            # Internal URL to Order API (service-to-service)
            - name: ORDER_SERVICE_URL
              value: "http://order-service-w08e1:8001"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service-w08e1
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
