name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > ~/.kube/config

      - name: Verify cluster connection
        run: kubectl get nodes

      # If your repo has ONE file (frontend.yaml), keep this block and remove the next one.
      - name: Deploy Frontend (single manifest)
        if: ${{ hashFiles('k8s/frontend.yaml') != '' }}
        run: |
          echo "Applying k8s/frontend.yaml"
          kubectl apply -f k8s/frontend.yaml

      # If your repo has split files, this block will run; the single-file block above will be skipped.
      - name: Deploy Frontend (split manifests)
        if: ${{ hashFiles('k8s/frontend-deployment.yaml') != '' || hashFiles('k8s/frontend-service.yaml') != '' }}
        run: |
          echo "Applying split frontend manifests"
          if [ -f k8s/frontend-deployment.yaml ]; then kubectl apply -f k8s/frontend-deployment.yaml; fi
          if [ -f k8s/frontend-service.yaml ]; then kubectl apply -f k8s/frontend-service.yaml; fi
