name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug ACR login server
        run: echo "Using ACR login server:${{ env.ACR_LOGIN_SERVER }}"

      - name: Docker login to ACR
        shell: bash
        run: |
          if [ -z "${{ env.ACR_LOGIN_SERVER }}" ]; then
            echo "ACR_LOGIN_SERVER is empty. Check secret AZURE_CONTAINER_REGISTRY."
            exit 1
          fi
          echo "${{ secrets.ACR_PASSWORD }}" | docker login "${{ env.ACR_LOGIN_SERVER }}" \
            -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build & Push Frontend Image
        shell: bash
        run: |
          docker build -t "${{ env.ACR_LOGIN_SERVER }}/frontend:latest" \
                       -t "${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}" \
                       ./frontend/
          docker push "${{ env.ACR_LOGIN_SERVER }}/frontend:latest"
          docker push "${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}"

      - name: Docker logout
        if: always()
        run: docker logout "${{ env.ACR_LOGIN_SERVER }}"
